import type {
  Banner,
  Category,
  Coupon,
  HomepageContent,
  Order,
  Product,
  Settings,
  User,
} from "@/types";

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000);

export const mockUsers: User[] = [
  {
    uid: "admin-1",
    name: "Admin",
    email: "admin@gmail.com",
    role: "admin",
    active: true,
    createdAt: daysAgo(90),
  },
  {
    uid: "cust-1",
    name: "John Smith",
    email: "john@example.com",
    role: "customer",
    active: true,
    createdAt: daysAgo(30),
  },
  {
    uid: "cust-2",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    role: "customer",
    active: true,
    createdAt: daysAgo(15),
  },
  {
    uid: "cust-3",
    name: "Mike Wilson",
    email: "mike@example.com",
    role: "customer",
    active: false,
    createdAt: daysAgo(60),
  },
];

export const mockCategories: Category[] = [
  { id: "cat-1", name: "T-Shirts", slug: "t-shirts", image: "https://picsum.photos/seed/cat1/400/400", active: true },
  { id: "cat-2", name: "Hoodies", slug: "hoodies", image: "https://picsum.photos/seed/cat2/400/400", active: true },
  { id: "cat-3", name: "Accessories", slug: "accessories", image: "https://picsum.photos/seed/cat3/400/400", active: true },
  { id: "cat-4", name: "Pants", slug: "pants", image: "https://picsum.photos/seed/cat4/400/400", active: false },
];

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    title: "Classic Roach Tee",
    slug: "classic-roach-tee",
    description: "Premium cotton t-shirt with iconic roach logo. Soft, breathable, and durable.",
    shortDescription: "Premium cotton tee with roach logo",
    price: 29.99,
    salePrice: 24.99,
    stock: 150,
    sku: "CRT-001",
    categoryId: "cat-1",
    tags: ["bestseller", "cotton"],
    images: ["https://picsum.photos/seed/prod1/600/600"],
    variants: [{ type: "size", value: "S" }, { type: "size", value: "M" }, { type: "size", value: "L" }, { type: "color", value: "Black" }],
    featured: true,
    active: true,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: "prod-2",
    title: "Roach Hoodie",
    slug: "roach-hoodie",
    description: "Cozy fleece hoodie perfect for everyday wear.",
    shortDescription: "Cozy fleece hoodie",
    price: 59.99,
    stock: 80,
    sku: "RH-001",
    categoryId: "cat-2",
    tags: ["hoodie", "winter"],
    images: ["https://picsum.photos/seed/prod2/600/600"],
    variants: [{ type: "size", value: "M" }, { type: "size", value: "L" }, { type: "color", value: "Navy" }],
    featured: true,
    active: true,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(5),
  },
  {
    id: "prod-3",
    title: "Roach Cap",
    slug: "roach-cap",
    description: "Adjustable cap with embroidered logo.",
    shortDescription: "Adjustable embroidered cap",
    price: 19.99,
    stock: 5,
    sku: "RC-001",
    categoryId: "cat-3",
    tags: ["accessories"],
    images: ["https://picsum.photos/seed/prod3/600/600"],
    variants: [{ type: "color", value: "Black" }],
    featured: false,
    active: true,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },
  {
    id: "prod-4",
    title: "Roach Joggers",
    slug: "roach-joggers",
    description: "Comfortable joggers for active lifestyle.",
    shortDescription: "Comfortable active joggers",
    price: 44.99,
    salePrice: 39.99,
    stock: 60,
    sku: "RJ-001",
    categoryId: "cat-4",
    tags: ["pants", "active"],
    images: ["https://picsum.photos/seed/prod4/600/600"],
    variants: [{ type: "size", value: "S" }, { type: "size", value: "M" }],
    featured: false,
    active: true,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },
  {
    id: "prod-5",
    title: "Vintage Roach Tee",
    slug: "vintage-roach-tee",
    description: "Retro-style tee with vintage wash.",
    shortDescription: "Retro vintage wash tee",
    price: 34.99,
    stock: 0,
    sku: "VRT-001",
    categoryId: "cat-1",
    tags: ["vintage"],
    images: ["https://picsum.photos/seed/prod5/600/600"],
    variants: [],
    featured: false,
    active: false,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(30),
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-1",
    userId: "cust-1",
    customerName: "John Smith",
    customerEmail: "john@example.com",
    items: [{ productId: "prod-1", title: "Classic Roach Tee", quantity: 2, price: 24.99, image: "https://picsum.photos/seed/prod1/600/600" }],
    subtotal: 49.98,
    tax: 4.0,
    shippingCharge: 5.99,
    discount: 0,
    total: 59.97,
    status: "pending",
    paymentStatus: "paid",
    shippingAddress: { name: "John Smith", email: "john@example.com", phone: "555-0101", address: "123 Main St", city: "Austin", state: "TX", zip: "78701", country: "US" },
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "ord-2",
    userId: "cust-2",
    customerName: "Sarah Johnson",
    customerEmail: "sarah@example.com",
    items: [{ productId: "prod-2", title: "Roach Hoodie", quantity: 1, price: 59.99 }],
    subtotal: 59.99,
    tax: 4.8,
    shippingCharge: 0,
    discount: 5,
    total: 60.79,
    status: "shipped",
    paymentStatus: "paid",
    shippingAddress: { name: "Sarah Johnson", email: "sarah@example.com", phone: "555-0102", address: "456 Oak Ave", city: "Dallas", state: "TX", zip: "75201", country: "US" },
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: "ord-3",
    userId: "cust-1",
    customerName: "John Smith",
    customerEmail: "john@example.com",
    items: [{ productId: "prod-3", title: "Roach Cap", quantity: 3, price: 19.99 }],
    subtotal: 59.97,
    tax: 4.8,
    shippingCharge: 5.99,
    discount: 0,
    total: 70.76,
    status: "delivered",
    paymentStatus: "paid",
    shippingAddress: { name: "John Smith", email: "john@example.com", phone: "555-0101", address: "123 Main St", city: "Austin", state: "TX", zip: "78701", country: "US" },
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
  },
  {
    id: "ord-4",
    userId: "cust-3",
    customerName: "Mike Wilson",
    customerEmail: "mike@example.com",
    items: [{ productId: "prod-4", title: "Roach Joggers", quantity: 1, price: 39.99 }],
    subtotal: 39.99,
    tax: 3.2,
    shippingCharge: 5.99,
    discount: 0,
    total: 49.18,
    status: "cancelled",
    paymentStatus: "refunded",
    shippingAddress: { name: "Mike Wilson", email: "mike@example.com", phone: "555-0103", address: "789 Pine Rd", city: "Houston", state: "TX", zip: "77001", country: "US" },
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
];

export const mockBanners: Banner[] = [
  { id: "ban-1", title: "Summer Collection", subtitle: "New arrivals up to 30% off", image: "https://picsum.photos/seed/ban1/1200/400", redirectUrl: "/collections/summer", position: 1, active: true },
  { id: "ban-2", title: "Free Shipping", subtitle: "On orders over $50", image: "https://picsum.photos/seed/ban2/1200/400", redirectUrl: "/shop", position: 2, active: true },
];

export const mockCoupons: Coupon[] = [
  { id: "coup-1", code: "WELCOME10", discountType: "percentage", discountValue: 10, minimumOrderAmount: 25, expiryDate: daysAgo(-30), usageLimit: 100, active: true },
  { id: "coup-2", code: "SAVE5", discountType: "fixed", discountValue: 5, minimumOrderAmount: 50, expiryDate: daysAgo(-60), usageLimit: 50, active: true },
  { id: "coup-3", code: "OLDCODE", discountType: "percentage", discountValue: 15, minimumOrderAmount: 0, expiryDate: daysAgo(10), usageLimit: 10, active: false },
];

export const mockSettings: Settings = {
  storeName: "MyRoach",
  logo: "https://picsum.photos/seed/logo/200/200",
  storeDescription: "Premium streetwear and accessories",
  contactEmail: "hello@myroach.com",
  phone: "+1 (555) 000-0000",
  address: "123 Commerce St, Austin, TX 78701",
  shippingCharge: 5.99,
  freeShippingThreshold: 50,
  taxPercentage: 8,
  socialLinks: { facebook: "https://facebook.com/myroach", instagram: "https://instagram.com/myroach", twitter: "https://twitter.com/myroach" },
  footerContent: "© 2026 MyRoach. All rights reserved.",
  policies: {
    returnPolicy: "30-day return policy on all items.",
    privacyPolicy: "We respect your privacy and protect your data.",
    termsAndConditions: "By using our site you agree to our terms.",
  },
};

export const mockHomepage: HomepageContent = {
  featuredCollectionIds: ["cat-1", "cat-2"],
  bestSellerIds: ["prod-1", "prod-2"],
  newArrivalIds: ["prod-4"],
  promoTitle: "Summer Sale",
  promoSubtitle: "Up to 30% off selected items",
  showFeatured: true,
  showBestSellers: true,
  showNewArrivals: true,
  showPromo: true,
};

// In-memory store for mock mutations
export const mockStore = {
  products: [...mockProducts],
  categories: [...mockCategories],
  orders: [...mockOrders],
  users: [...mockUsers],
  banners: [...mockBanners],
  coupons: [...mockCoupons],
  settings: { ...mockSettings },
  homepage: { ...mockHomepage },
};
